mysite/api/urls.py
from django.urls import path, include
from .views import TestStepStats
from rest_framework.routers import DefaultRouter
# from io_module.views import IOModuleView
from myapp.views import ConfigView
app_name = "api"

router = DefaultRouter()
# router.register(r'stepstat/', TestStepStats, basename='stepstat')
# router.register(r'io', IOModuleView, basename='io')


urlpatterns = [
    # path('config/', ConfigView.as_view(), name='config'),
    path("stepstat/", TestStepStats.as_view({"get": "list", "post": "create"}), name="stepstat"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView
)
# from myapp.views import ConfigView

urlpatterns = [
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path("", TemplateView.as_view(template_name="testcase/tchome.html"), name="home"),
    path("admin/", admin.site.urls),
    path("io_module/", include("io_module.urls"), name="io_module"),
    path("api/", include("api.urls"), name='api'),
    path("auth/", include("users.urls"), name='users'),
    path("restapi/", include('rest_framework.urls'), name="rest_framework"), # UserRegistrationViewSet
    path("config/", include("config.urls"), name='config'),
    path("testcase/", include("testcase.urls"), name='testcase'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()


# path("", TemplateView.as_view(template_name="index.html"), name="home"),
    # path("", TemplateView.as_view(template_name="index.html"), name="home"),
    
    # path("myapp/", include("myapp.urls")),
    # path("myapp/", ConfigView.as_view(), name="config_api_view"),
    # path("testcase/", include("testcase.urls")),

mysite/testcase/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from .views import TestCaseView, TestStepDetail, TestStepStats, TestCaseListRestAPI
from rest_framework.routers import DefaultRouter

app_name = "testcase"

router = DefaultRouter()
router.register("tcs", TestCaseListRestAPI, basename="tcs") # list of test cases

urlpatterns = [
    path("", include(router.urls)),
]


# router.register("api", TestStepStats, basename="teststep")

mysite/users/urls.py
from django.urls import path, include
# from .views import UserRegistrationViewSet, UserAuthViewSet
from .views import UserRegistrationViewSet, UserLoginAPIView, UserProfileAPIView, UserChangePasswordAPIView,\
      SendResetPasswordEmailAPIView, ValidateResetPasswordEmailAPIView, UserLogoutAPIView
from rest_framework.routers import DefaultRouter

app_name = "users"

router = DefaultRouter()


router.register(r"users", UserRegistrationViewSet, basename="userapi")

urlpatterns = [
    path("", include(router.urls)),
    path("login/", UserLoginAPIView.as_view(), name="login"),
    path("logout/", UserLogoutAPIView.as_view(), name="logout"),
    path("profile/", UserProfileAPIView.as_view(), name="profile"),
    path("change_password/", UserChangePasswordAPIView.as_view(), name="change_password"),
    path('send-reset-password-email/', SendResetPasswordEmailAPIView.as_view(), name='send-reset-password-email'),
    path('reset_password/<uid>/<token>/', ValidateResetPasswordEmailAPIView.as_view(), name='reset_password'),
]


# path("register/", UserRegistrationViewSet.as_view({"post": "create"}), name="register"),

# router.register("", UserRegistrationViewSet, basename="userapi")
# router.register("login", UserAuthAPIView.as_view({"post": "create"}), basename="login")

# urlpatterns = [
#     path("", include(router.urls)),
#     path("/login/", UserAuthAPIView.as_view(), name="login")
# ]

mysite/testcase/models.py
from django.db import models
import json
from users.models import User

# Create your models here.


# class TestCase(models.Model):
#     cqid = models.CharField(max_length=20)
#     title = models.CharField(max_length=100)
#     summary = models.TextField(max_length=2000)
#     # test_steps_list = models.ManyToManyField('TestStep')

#     def __str__(self) -> str:
#         return self.title

# class TestStep(models.Model):
#     test_case = models.ForeignKey(TestCase, on_delete=models.CASCADE, related_name='test_steps')
#     step = models.CharField(max_length=10000)

#     def __str__(self):
#         return self.step

class TestCase(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cqid = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    summary = models.TextField(max_length=2000)
    test_steps_list = models.ManyToManyField("TestStep")  # using reverse relation ship name : test_steps_list
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.title

class TestStep(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test_cases = models.ManyToManyField(TestCase, related_name='teststep')
    step = models.JSONField(null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now_add=True)
    # use_count = models.IntegerField(default=0)

    def __str__(self):
        return json.dumps(self.step) if self.step else ""

mysite/testcase/views.py
from django.db import models
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse
from django.views.generic import View, DeleteView, UpdateView, ListView, DetailView
from .models import TestStep, TestCase
import time, json
from django.http import JsonResponse
from django.core.serializers import serialize
from django.db.models import Q, Value
# from myapp.models import ConfigModel
from io_module.models import IOModel
from api.serializers import TestCaseSerializer, TestStepSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework import viewsets
from rest_framework.renderers import BrowsableAPIRenderer, TemplateHTMLRenderer
from rest_framework.authentication import SessionAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from .serializers import TestCaseListSerializer
from rest_framework import status
from .renderers import TCRenderer
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.

class TestCaseView(View):
    template_name = '/testcase/success.html'
    def post(self, request, *args, **kwargs):
        body = request.body.decode('utf-8')
        data = json.loads(body)
        steps = data["moduleForm"]
        print("Steps received is : {}".format(steps))
        cqid = 1
        title = "Dummy_TC_3"
        summary = "Testing Model"
        tcid, created = TestCase.objects.get_or_create(cqid=cqid, title=title, summary=summary)
        print("Created : {}".format(created))

        # Create and associate TestStep instances with the TestCase
        for step in steps:
            del step["csrfmiddlewaretoken"]
            test_step, _ = TestStep.objects.get_or_create(step=step)
            test_step.test_cases.set([tcid])
            tcid.test_steps_list.add(test_step)
            test_step.save()
        tcid.save()
        response = {"resp": "Submit successful from testcase view"}
        test_steps = tcid.test_steps_list.all()
        for test_step in test_steps:
            print(test_step.step)
        return JsonResponse(response)

class TestStepStats(View):
    def get(self, request, *args, **kwargs):
        print("Request for stats : {}".format(request.GET))
        print("Self.Request for stats : {}".format(self.request.GET))
        request_data = self.request.GET
        step = {k: v[0] for k, v in request_data}
        print(f"Step data is : {step}")

        query = Q()
        for key, value in step.items():
            query &= Q(**{f'step__{key}': value})
        print(f"Query is : {query}")
        response = {
            "pk": False,
            "fetched": False,
            "step_stats": {},
            "total_step_by_params": 0,
            "num_tc_associated": 0, 
        }
        print("Fetching Test Step Stats : step {}".format(step))
        pk = False
        fetched = False
        total_step_by_params = 0
        num_tc_associated = 0
        try:
            # test_step = TestStep.objects.filter(step=step).first()
            # all = TestStep.objects.all()
            # test_step = TestStep.objects.filter(step=Value(step)
            """
            # Assuming you have a queryset named `queryset`
            first_instance = queryset.first()  # Get the first model instance from the queryset
            pk = getattr(first_instance, 'pk', None)  # Retrieve the primary key (pk) attribute

            # You can also directly access the `pk` attribute
            pk = first_instance.pk

            # If you want to retrieve the primary keys of all instances in the queryset
            pks = queryset.values_list('pk', flat=True)  # Returns a list of primary keys            
            """
            test_step = TestStep.objects.filter(Q(step__raid=step["raid"]))
            total_step_by_params = len(test_step)

            exact_step = test_step.filter( 
                step__pdcount=step["pdcount"],
                step__vdcount=step["vdcount"],
                step__size=step["size"],
                step__spans=step["spans"],
                step__stripe=step["stripe"],
                step__dtabcount=step["dtabcount"],
                step__hotspare=step["hotspare"],
                step__init=step["init"],
                step__readpolicy=step["readpolicy"],
                step__writepolicy=step["writepolicy"],
                step__repeat=step["repeat"]
            )
            print("Exact step : {}".format(exact_step))
            # num_tcs = exact_step.first().test_cases.all().count()   # Use the related name
            num_tcs = TestCase.objects.filter(test_steps_list__in=exact_step)   # Use the related name
            fetched = exact_step.exists()
            if fetched:
                pk = getattr(exact_step.first(), 'pk', None)
                num_tc_associated = exact_step.first()
            else:
                pk = False
            print("Test Cases : {}".format(total_step_by_params))
            print("Test step : {}".format(test_step))
            print("Exact Test step : {}".format(exact_step))
            print("Exact Test num_tcs : {}".format(num_tcs))
            print("Exact Test step num_tc_associate : {}".format(num_tc_associated))
        # except (TestStep.DoesNotExist, AttributeError):
        except Exception as e:
            print("Exception is : {}".format(e))
            test_step = None
        print("Test step fetched PK : {}".format(pk))
        # Extract testcases details if fetched
        # test_case_details = self.get_test_case_details(test_step)

        # serialized_test_step = serialize('json', list(exact_step)) if fetched else {}
        serialized_test_step = TestStepSerializer(exact_step, many=True) # if fetched else {}
        print("Serialized Test Step : {}".format(serialized_test_step))
        # print("Serialized Test Step : {}".format(serialized_test_step.data))
        
        num_tcs_serial = serialize('json', list(num_tcs)) if fetched else {}
        response = {
            "fetched": fetched,
            "data": serialized_test_step.data if serialized_test_step.data is not None else {},
            # "data": serialized_test_step,
            "pk": pk,
            "total_step_by_params": total_step_by_params,
            "num_tc_associated": num_tcs_serial
        }
        print("Response is : {}".format(response))
        return JsonResponse(response)


    # def get_test_case_details(self, test_step):
    #     return test_step.test
    
class TestCaseList(ListView):
    model = TestCase
    queryset = TestCase.objects.order_by('updated_on')


class TestStepDetail(DetailView):
    """
    The default behavior of the `render_to_response` method in Django's `DetailView`
    is to render a template with the provided context and return an HTML response.
    By default, it uses the template specified in the `template_name` attribute
    of the view or follows the naming convention to determine the template name.

    When you override the `render_to_response` method in the example I provided,
    you are changing the default behavior to return a JSON response instead of
    rendering an HTML template. The overridden method constructs the JSON
    response by extracting the desired data from the context and serializing
    it into JSON using the `JsonResponse` class.

    It's important to note that the default behavior of `render_to_response`
    may vary depending on the specific class being used (e.g., `DetailView`,
    `ListView`, etc.) and can be further customized based on your requirements.
    """
    model = TestStep
    context_object_name = "teststep_detail"
    queryset = TestStep.objects.prefetch_related('test_cases').order_by('updated_on')
    print("Returning QuerySet : {}".format(queryset))

    def render_to_response(self, context, **response_kwargs):
        teststep_detail = context.get(self.context_object_name)
        print("Test Step Details : {}".format(teststep_detail))
        print("All TC Step Details : {}".format(teststep_detail.test_cases.all()))
        data = {
            'step': teststep_detail.step,
            'test_cases': [
                {
                    'cqid': testcase.cqid,
                    'title': testcase.title,
                    'summary': testcase.summary,
                    "updated_on": testcase.updated_on
                }
                for testcase in teststep_detail.test_cases.all()
            ]
        }
        print("Data being sent : {}".format(data))
        return JsonResponse(data, **response_kwargs)

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['teststep_detail_list'] = TestStep.objects.all()  # Replace this with your desired queryset
    #     print("Context data is : {}".format(context))
    #     return context

class TestCaseListRestAPI(viewsets.ModelViewSet):
    queryset = TestCase.objects.all()
    renderer_classes = [TCRenderer, BrowsableAPIRenderer, TemplateHTMLRenderer]
    authentication_classes = [SessionAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = TestCaseListSerializer
    template_name = "testcase/tclist.html"

    def list(self, request, *args, **kwargs):
        print(f"Request : {request.__dict__}")
        accepted_media_type = request.accepted_media_type
        print(f"Accepted media type : {accepted_media_type}")
        paginator = Paginator(self.queryset, 25) # Show 25 contacts per page
        user = request.user
        tc_list = self.queryset.filter(user=user)
        serializer = self.serializer_class(instance=tc_list, many=True)
        print(f"TC List User is : {user}")
        print(f"TC list is      : {tc_list}")
        print(f"Serializer is   : {serializer}")
        print(f"Serializer data : {serializer.data}")
        try:
            data = paginator.page(serializer.data)
        except PageNotAnInteger:

mysite/testcase/templates/testcase/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>Home Page</title>
</head>
{% load static %}
<body>
    <nav class="shadow-lg">
        <div class="flex flex-wrap justify-between ml-5 items-center mx-auto px-4 py-2.5">
            <a href="" class="flex items-center">
                <img class="h-15 mr-3" src="https://cdn2.iconfinder.com/data/icons/artificial-intelligence-6/64/ArtificialIntelligence12-512.png" height=50 width=50 alt="">
                <span class="self-center text-xml font-semibold">Wingman Shadow</span>
            </a>
            
            <div class="flex items-center">
                <a href="" class="mr-6 text=sm font-medium text-grey-500">Dashboard</a>
                <a href='/testcase/tcs/' class="mr-6 text-sm font-medium text-grey-500" id="tcListUrl">Test Cases</a>
                <a href="/" class="mr-6 text=sm font-medium text-grey-500">Stats</a>
                <a href="{% url 'users:profile' %}" class="mr-6 text=sm font-medium text-grey-500">My Profile</a>
                <a href="" class="mr-6 text=sm font-medium text-grey-500" id="logout-link">Logout</a>
            </div>

        </div>
    </nav>

    {% block content %}
    
    
    {% endblock content %}

</body>
<script src="{% static '/users/js/logout.js' %}"></script>
</html>

mysite/testcase/templates/testcase/input_form.html
{% comment %} {% extends 'testcase/tchome.html' %} {% endcomment %}

{% block tchome %}
{% load static %}
<link rel="stylesheet" href="{% static 'testcase/css/module_form.css' %}">



<div class="flex justify-start w-full h-full hover:shadow-lg rounded-lg">
    <div class="w-full items-center">
        <div class="flex">
            <div class="text-grey-300 module-name text-xl font-bold m-10" id="module-name">Add {{ module_name|upper  }}</div>
        </div>
        <div class="flex flex-wrap">
            {% comment %} <form action="{% url 'io:io-list' %}" method="POST" id="module-form" class="w-full"> {% endcomment %}
            <form action="" method="POST" id="module-form" class="w-full">
                {% csrf_token %}
                <div class="flex flex-wrap">
                    {% for field in form %}
                    <div class="w-full flex flex-col mb-1">
                        <div class="flex flex-row">
                            <div class="w-1/3">
                                <label class="text-lg text-bold justify-start ml-8">{{ field.label_tag }}</label>
                            </div>
                            <div class="w-2/3 border border-gray-300 rounded-lg mr-10 px-2">
                                {{ field }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                
                    {{ form.errors }}
                    <div class="flex w-full flex-col-reverse">
                        <div class="w-1/5 submit-step bg-green-500 px-2 py-2 text-white text-center text-sm font-bold rounded-sm mt-5 ml-auto mr-10">
                            <input type="submit" value="Submit Step" id="submit-step">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div> 
</div>

{% endblock tchome %}

mysite/testcase/templates/testcase/success.html
{% extends 'base.html' %}

{% block content %}

<h3>Submitted successfully</h3>

{% endblock content %}

mysite/testcase/templates/testcase/tchome.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'testcase/css/module_form.css' %}">
{% block content %}

<h2>Welcome to tchome</h2>
{% comment %} <div class="flex justify-between items-stretch space-x-5"> {% endcomment %}

    <!-- ===================================== -->
    <!--     Block for Showing Modules List    -->
    <!-- ===================================== -->
    <div class="flex h-screen">
        <!-- NAVBAR -->
        <div class="bg-gray-900 text-white w-1/8">
            <div class="flex justify-between items-center py-4 px-6">
                <div class="items-left">
                    <div class="text-gray-300 text-xl text-left font-bold p-5 mr-5">Wingman Dashboard</div>
                    <h5>User {{user}}</h5>
                    <h5>User authenticated : {{user.is_authenticated}}</h5>
                        <!-- Sidebar content goes here -->
                        <ul class="py-4 grow">
                            <li class="px-4 py-2 hover:bg-yellow-300 hover:font-bold">Test Modules</li>

                            
                                <ul class="px-4 py-2" id="module-list">
                                  <li class="hover:bg-yellow-300 hover:font-bold rounded-sm px-4 py-2"><a href="#" data-appname="config">Config</a></li>
                                  <li class="hover:bg-yellow-300 hover:font-bold rounded-sm px-4 py-2"><a href="#" data-appname="io">IO</a></li>
                                  <!-- Add more app links here -->
                                </ul>


                            <li class="px-4 py-2 hover:bg-yellow-300 hover:font-bold">My Test Cases</li>
                            <li class="px-4 py-2 hover:bg-yellow-300 hover:font-bold">Settings</li>
                            {% comment %} <ul class="space-y-2"> {% endcomment %}
                            <a href="{% url 'users:profile' %}"><li class="px-4 py-2 mt-2 bg-gray-400 rounded shadow">Profile</li></a>
                            <li class="px-4 py-2 mt-2 bg-gray-400 rounded shadow">Settings</li>
                            <!-- Add more menu items as needed -->
                        </ul>
                        {% comment %} <div class="grow h-20"></div> <!-- This creates empty space to push the next items to the bottom -->
                        <div class="p-4 self-auto">
                            <ul class="space-y-2">
                            <li class="p-2 bg-gray-400 rounded shadow">Profile</li>
                            <li class="p-2 bg-gray-400 rounded shadow">Settings</li>
                            </ul>
                        </div> {% endcomment %}
                </div>
            </div>
        </div>
    
        <!-- MAIN SCREEN -->
        <div class="w-7/8 p-6">
            <div class="flex flex-wrap justify-center">
                <!-- ===================================== -->
                <!--      Block for Showing Module Form    -->
                <!-- ===================================== -->
                
                <div class="flex-item w-full h-3/4">
                    {% comment %} <div class="grid grid-rows-4 grid-flow-col gap-4 h-full"> {% endcomment %}
                    <div class="grid grid-rows-4 grid-cols-5 gap-4 h-full">

                        <!-- MODULE FORM -->
                        <div class="row-span-4 col-span-2 p-2 shadow-lg rounded-sm" id="module-form-container">
                            {% block tchome %}
                            {% comment %} All forms will be rendered here {% endcomment %}
                            {% endblock tchome %}
                        </div>
                    
                        <!-- TS STATS -->
                        <div class="row-span-2 col-span-3 p-2 shadow-lg rounded-sm">
                            
                            <div class="grid grid-rows-10 gap-1 w-full h-full">
                                <div class="row-span-1 p-2 col-span-3 rounded-sm">
                                    {% comment %} <div class="text-xl font-bold px-2 py-1 bg-gradient-to-r from-indigo-600 to-pink-500 text-white text-center rounded-lg"> {% endcomment %}
                                    <div class="text-xl font-bold px-2 py-1 bg-gray-900 text-white text-center rounded-lg">
                                        Step Analytics
                                    </div>
                                </div>

                                <div class="row-span-9 p-2 col-span-3 rounded-sm">
                                    {% block analytics %}

                                        <div class="grid grid-cols-2 grid-rows-2 gap-1 w-full h-full max-w-5xl rounded-sm">
                                            <div class="row-span-1 col-span-1 rounded-sm">
                                                <div id="chart-container" class="h-full shadow hover:shadow-2xl m-1 hover:scale-125 hover:opacity-100">
                                                    {% comment %} {% include 'testcase/teststep_detail.html' %} {% endcomment %}
                                                    <!-- Step Usage chart -->
                                                    <canvas id="myChart-0"></canvas>
                                                </div>
                                            </div>
                                            
                                            {% comment %} <!-- Modal -->
                                            <div id="canvasModal" class="modal">
                                                <div class="modal-content">
                                                <span class="close">&times;</span>
                                                <canvas id="modalCanvas"></canvas>
                                                </div>
                                            </div> {% endcomment %}

                                            <!-- Doughnut chart -->
                                            <div class="row-span-1 col-span-1 rounded-sm">
                                                <div id="chart-container-2" class="h-full shadow hover:shadow-2xl m-1 hover:scale-125 hover:opacity-100">
                                                    <canvas id="myChart-2"></canvas>
                                                </div>            
                                            </div>

                                            <div class="row-span-1 col-span-1 rounded-sm">
                                                <div id="teststep-container" class="h-full shadow hover:shadow-2xl m-1 text-center p-2 hover:scale-125 hover:opacity-100">
                                                    <p id="myp-1"></p>
                                                </div>            
                                            </div>
                                            
                                            <div class="row-span-1 col-span-1 rounded-sm">
                                                <div id="chart-container-3" class="h-full shadow hover:shadow-2xl m-1 text-left p-2 hover:scale-125 hover:opacity-100">
                                                    <div class="max-h-[200px] overflow-y-auto border-1 exact-tc h-full">
                                                        <p id="myp-2"></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    {% endblock analytics %}
                                </div>
                            </div>
                        </div>
                        
                        <!-- TC CART -->
                        <div class="row-span-2 p-2 col-span-3 shadow-lg rounded-sm">
                            
                            <div class="grid grid-rows-10 grid-flow-row gap-1 w-full h-full">
                                
                                <!-- TC CART HEADER -->
                                <div class="row-span-1 p-2 col-span-2 rounded-sm">
                                    {% comment %} <div class="text-xl font-bold px-2 py-1 bg-gradient-to-r from-indigo-600 to-pink-500 text-white text-center rounded-lg"> {% endcomment %}
                                    <div class="text-xl font-bold px-2 py-1 bg-gray-900 text-white text-center rounded-lg">
                                        Test Case Cart
                                    </div>
                                </div>
                                
                                <!-- TC CART LEFT PANE -->
                                <div class="row-span-8 p-2 col-span-1 rounded-sm">
                                    {% comment %} <div class="max-h-[200px] overflow-y-auto border-0 tc-cart-left h-full"> {% endcomment %}
                                        Cool things in making. Hold my &#127866;
                                    {% comment %} </div> {% endcomment %}
                                </div>
                                
                                <!-- TC CART RIGHT PANE -->
                                <div class="row-span-8 p-2 col-span-1 rounded-sm">
                                    <div class="max-h-[250px] overflow-y-auto border-1 tc-cart h-full">                                        
                                        So empty here...submit your first test step!
                                    </div>
                                </div>

                                <!-- TC CART BOTTOM PANE -->
                                <div class="row-span-1 p-2 col-span-2 rounded-sm">
                                    <div class="flex flex-row-reverse justify-stretch gap-4">
                                        <div class="bg-green-500 text-white text-center rounded-sm font-bold text-sm px-2 py-2 submit-to-db" id="submit-to-db">
                                            <input type="submit" value="Save in DB">
                                        </div>

                                        <div class="bg-green-500 text-white text-center rounded-sm font-bold text-sm px-2 py-2 submit-to-db" id="download-tc">
                                            <input type="submit" value="Download TC">
                                        </div>
                                    </div>
                                </div>
                            
                            <div>
                        </div>

                    </div>
                </div>
                
                {% comment %} <!-- ===================================== -->
                <!--    Block for Showing Test Step Cart   -->
                <!-- ===================================== -->
                <div class="text-xl font-bold mt-4 mb-2 px-5 py-5 bg-gradient-to-r from-indigo-600 to-pink-500 text-white text-center">
                    Test Case
                </div>
                
                <div class="max-h-[300px] overflow-y-auto border-0">
                    <div class="tc-cart p-4">
                            So empty here...submit your first test step!
                    </div>
                </div>

                <div class="text-bold">
                    <div class="bg-green-500 text-white text-center rounded-sm m-4 font-bold px-2 py-3 submit-to-db" id="submit-to-db">
                        <input type="submit" value="Submit to DB">
                    </div>
                </div> {% endcomment %}
            </div>
        </div>
    </div>

<script type="module"  src="{% static 'testcase/js/moduleUrlMap.js' %}"></script>
<script type="module" src="{% static 'testcase/js/test_step.js' %}"></script>
<script type="module" src="{% static 'testcase/js/test_module.js' %}"></script>
<script src="{% static 'users/js/logout.js' %}"></script>

{% endblock content %}